import { assertEquals } from "@std/assert";
import { join } from "node:path";
import { readFileSync } from "node:fs";

import { mapping, Validator } from "../../src/mod.ts";

Deno.test("TestCetardio", () => {
  const metadata = [
    JSON.parse(
      readFileSync(join("__tests__", "payloads", "cetardio.json"), "utf8"),
    ),
  ];

  const validatorsReceivedFromFrontend: Array<keyof typeof mapping> = [
    "hasRequiredKeysValidator",
    "compareRootKeys",
    "compareRootValues",
    "keyLowerCase",
    "keyAttributesValidator",
    "compareAttributesKeys",
    "keyWhiteSpace",
    "keyNameValidator",
    "keyLength",
    "keyMediaTypeValidator",
    "keyMediaValidator",
    "keyImageValidator",
    "keyFilesValidator",
    "keyDescriptionValidator",
    "keyAlphanumeric",
    "duplicateImage",
    "duplicateAssetName",
    "duplicateKeysValidator",
    "keyTraitsValidator",
  ];

  const mainValidator = new Validator("Main");
  for (const validator of validatorsReceivedFromFrontend) {
    mainValidator.Enable(new mapping[validator]());
  }

  for (const asset_metadata of metadata) {
    mainValidator.Execute(
      Object.keys(asset_metadata)[0],
      Object.values(asset_metadata)[0],
      metadata,
    );
  }

  const result = mainValidator.GetResults();

  assertEquals(result, [
    {
      state: "success",
      message: "All required keys are present.",
      input: {
        head: "CETARDIO whitelist",
        name: "CETARDIO WL",
        image: "ipfs://QmNZb1qc7dY8m1zRgwfqTEztUxdF9eL9h666tbK95cAwP3",
        Discord: "https://discord.gg/MyProject",
        Twitter: "https://twitter.com/MyProject",
        Website: "https://myproject.com",
        mediaType: "image/png",
        description: "My cool NFT project description",
      },
      output: undefined,
      assetName: "CETARDIOwhitelist4",
      validatorId: "has-required-keys",
    },
    {
      state: "success",
      message: "No similar keys found.",
      input: {
        head: "CETARDIO whitelist",
        name: "CETARDIO WL",
        image: "ipfs://QmNZb1qc7dY8m1zRgwfqTEztUxdF9eL9h666tbK95cAwP3",
        Discord: "https://discord.gg/MyProject",
        Twitter: "https://twitter.com/MyProject",
        Website: "https://myproject.com",
        mediaType: "image/png",
        description: "My cool NFT project description",
      },
      output: undefined,
      assetName: "CETARDIOwhitelist4",
      validatorId: "compare-root-keys",
    },
    {
      state: "success",
      message: "No similar values found.",
      input: {
        head: "CETARDIO whitelist",
        name: "CETARDIO WL",
        image: "ipfs://QmNZb1qc7dY8m1zRgwfqTEztUxdF9eL9h666tbK95cAwP3",
        Discord: "https://discord.gg/MyProject",
        Twitter: "https://twitter.com/MyProject",
        Website: "https://myproject.com",
        mediaType: "image/png",
        description: "My cool NFT project description",
      },
      output: undefined,
      assetName: "CETARDIOwhitelist4",
      validatorId: "compare-root-values",
    },
    {
      state: "warning",
      message: {
        message: "Some keys do not adhere to Lower Case formatting.",
        warnings: [
          { key: "Discord", path: "Discord" },
          { key: "Twitter", path: "Twitter" },
          { key: "Website", path: "Website" },
          { key: "mediaType", path: "mediaType" },
        ],
      },
      input: {
        head: "CETARDIO whitelist",
        name: "CETARDIO WL",
        image: "ipfs://QmNZb1qc7dY8m1zRgwfqTEztUxdF9eL9h666tbK95cAwP3",
        Discord: "https://discord.gg/MyProject",
        Twitter: "https://twitter.com/MyProject",
        Website: "https://myproject.com",
        mediaType: "image/png",
        description: "My cool NFT project description",
      },
      output: undefined,
      assetName: "CETARDIOwhitelist4",
      validatorId: "key-lower-case",
    },
    {
      state: "success",
      message: "`attributes` field is valid.",
      input: {
        head: "CETARDIO whitelist",
        name: "CETARDIO WL",
        image: "ipfs://QmNZb1qc7dY8m1zRgwfqTEztUxdF9eL9h666tbK95cAwP3",
        Discord: "https://discord.gg/MyProject",
        Twitter: "https://twitter.com/MyProject",
        Website: "https://myproject.com",
        mediaType: "image/png",
        description: "My cool NFT project description",
      },
      output: {},
      assetName: "CETARDIOwhitelist4",
      validatorId: "key-attributes",
    },
    {
      state: "warning",
      message: [
        "The `attributes` key might be missing from the supplied metadata, or an invalid threshold value may have been set.",
      ],
      input: {
        head: "CETARDIO whitelist",
        name: "CETARDIO WL",
        image: "ipfs://QmNZb1qc7dY8m1zRgwfqTEztUxdF9eL9h666tbK95cAwP3",
        Discord: "https://discord.gg/MyProject",
        Twitter: "https://twitter.com/MyProject",
        Website: "https://myproject.com",
        mediaType: "image/png",
        description: "My cool NFT project description",
      },
      output: undefined,
      assetName: "CETARDIOwhitelist4",
      validatorId: "compare-attributes-keys",
    },
    {
      state: "success",
      message: "All checks passed. No issues detected.",
      input: {
        head: "CETARDIO whitelist",
        name: "CETARDIO WL",
        image: "ipfs://QmNZb1qc7dY8m1zRgwfqTEztUxdF9eL9h666tbK95cAwP3",
        Discord: "https://discord.gg/MyProject",
        Twitter: "https://twitter.com/MyProject",
        Website: "https://myproject.com",
        mediaType: "image/png",
        description: "My cool NFT project description",
      },
      output: undefined,
      assetName: "CETARDIOwhitelist4",
      validatorId: "key-white-space",
    },
    {
      state: "success",
      message: "`name` field is valid.",
      input: {
        head: "CETARDIO whitelist",
        name: "CETARDIO WL",
        image: "ipfs://QmNZb1qc7dY8m1zRgwfqTEztUxdF9eL9h666tbK95cAwP3",
        Discord: "https://discord.gg/MyProject",
        Twitter: "https://twitter.com/MyProject",
        Website: "https://myproject.com",
        mediaType: "image/png",
        description: "My cool NFT project description",
      },
      output: { name: "CETARDIO WL" },
      assetName: "CETARDIOwhitelist4",
      validatorId: "key-name",
    },
    {
      state: "success",
      message: "All checks passed. No issues detected.",
      input: {
        head: "CETARDIO whitelist",
        name: "CETARDIO WL",
        image: "ipfs://QmNZb1qc7dY8m1zRgwfqTEztUxdF9eL9h666tbK95cAwP3",
        Discord: "https://discord.gg/MyProject",
        Twitter: "https://twitter.com/MyProject",
        Website: "https://myproject.com",
        mediaType: "image/png",
        description: "My cool NFT project description",
      },
      output: undefined,
      assetName: "CETARDIOwhitelist4",
      validatorId: "key-length",
    },
    {
      state: "success",
      message: "`mediaType` field is valid.",
      input: {
        head: "CETARDIO whitelist",
        name: "CETARDIO WL",
        image: "ipfs://QmNZb1qc7dY8m1zRgwfqTEztUxdF9eL9h666tbK95cAwP3",
        Discord: "https://discord.gg/MyProject",
        Twitter: "https://twitter.com/MyProject",
        Website: "https://myproject.com",
        mediaType: "image/png",
        description: "My cool NFT project description",
      },
      output: { mediaType: "image/png" },
      assetName: "CETARDIOwhitelist4",
      validatorId: "key-media-type",
    },
    {
      state: "success",
      message: "`media` field is valid.",
      input: {
        head: "CETARDIO whitelist",
        name: "CETARDIO WL",
        image: "ipfs://QmNZb1qc7dY8m1zRgwfqTEztUxdF9eL9h666tbK95cAwP3",
        Discord: "https://discord.gg/MyProject",
        Twitter: "https://twitter.com/MyProject",
        Website: "https://myproject.com",
        mediaType: "image/png",
        description: "My cool NFT project description",
      },
      output: {},
      assetName: "CETARDIOwhitelist4",
      validatorId: "key-media",
    },
    {
      state: "success",
      message: "`image` field is valid.",
      input: {
        head: "CETARDIO whitelist",
        name: "CETARDIO WL",
        image: "ipfs://QmNZb1qc7dY8m1zRgwfqTEztUxdF9eL9h666tbK95cAwP3",
        Discord: "https://discord.gg/MyProject",
        Twitter: "https://twitter.com/MyProject",
        Website: "https://myproject.com",
        mediaType: "image/png",
        description: "My cool NFT project description",
      },
      output: {
        image: "ipfs://QmNZb1qc7dY8m1zRgwfqTEztUxdF9eL9h666tbK95cAwP3",
      },
      assetName: "CETARDIOwhitelist4",
      validatorId: "key-image",
    },
    {
      state: "success",
      message: "`files` field is valid.",
      input: {
        head: "CETARDIO whitelist",
        name: "CETARDIO WL",
        image: "ipfs://QmNZb1qc7dY8m1zRgwfqTEztUxdF9eL9h666tbK95cAwP3",
        Discord: "https://discord.gg/MyProject",
        Twitter: "https://twitter.com/MyProject",
        Website: "https://myproject.com",
        mediaType: "image/png",
        description: "My cool NFT project description",
      },
      output: {},
      assetName: "CETARDIOwhitelist4",
      validatorId: "key-files",
    },
    {
      state: "success",
      message: "`description` field is valid.",
      input: {
        head: "CETARDIO whitelist",
        name: "CETARDIO WL",
        image: "ipfs://QmNZb1qc7dY8m1zRgwfqTEztUxdF9eL9h666tbK95cAwP3",
        Discord: "https://discord.gg/MyProject",
        Twitter: "https://twitter.com/MyProject",
        Website: "https://myproject.com",
        mediaType: "image/png",
        description: "My cool NFT project description",
      },
      output: { description: "My cool NFT project description" },
      assetName: "CETARDIOwhitelist4",
      validatorId: "key-description",
    },
    {
      state: "success",
      message: "All checks passed. No issues detected.",
      input: {
        head: "CETARDIO whitelist",
        name: "CETARDIO WL",
        image: "ipfs://QmNZb1qc7dY8m1zRgwfqTEztUxdF9eL9h666tbK95cAwP3",
        Discord: "https://discord.gg/MyProject",
        Twitter: "https://twitter.com/MyProject",
        Website: "https://myproject.com",
        mediaType: "image/png",
        description: "My cool NFT project description",
      },
      output: undefined,
      assetName: "CETARDIOwhitelist4",
      validatorId: "key-alphanumeric",
    },
    {
      state: "success",
      message: "All checks passed. No issues detected.",
      input: {
        head: "CETARDIO whitelist",
        name: "CETARDIO WL",
        image: "ipfs://QmNZb1qc7dY8m1zRgwfqTEztUxdF9eL9h666tbK95cAwP3",
        Discord: "https://discord.gg/MyProject",
        Twitter: "https://twitter.com/MyProject",
        Website: "https://myproject.com",
        mediaType: "image/png",
        description: "My cool NFT project description",
      },
      output: undefined,
      assetName: "CETARDIOwhitelist4",
      validatorId: "duplicate-image",
    },
    {
      state: "success",
      message: "All checks passed. No issues detected.",
      input: {
        head: "CETARDIO whitelist",
        name: "CETARDIO WL",
        image: "ipfs://QmNZb1qc7dY8m1zRgwfqTEztUxdF9eL9h666tbK95cAwP3",
        Discord: "https://discord.gg/MyProject",
        Twitter: "https://twitter.com/MyProject",
        Website: "https://myproject.com",
        mediaType: "image/png",
        description: "My cool NFT project description",
      },
      output: undefined,
      assetName: "CETARDIOwhitelist4",
      validatorId: "duplicate-asset-name",
    },
    {
      state: "success",
      message: "No significant duplicates detected in the metadata.",
      input: {
        head: "CETARDIO whitelist",
        name: "CETARDIO WL",
        image: "ipfs://QmNZb1qc7dY8m1zRgwfqTEztUxdF9eL9h666tbK95cAwP3",
        Discord: "https://discord.gg/MyProject",
        Twitter: "https://twitter.com/MyProject",
        Website: "https://myproject.com",
        mediaType: "image/png",
        description: "My cool NFT project description",
      },
      output: undefined,
      assetName: "CETARDIOwhitelist4",
      validatorId: "duplicate-keys",
    },
    {
      state: "success",
      message: "`traits` field is valid.",
      input: {
        head: "CETARDIO whitelist",
        name: "CETARDIO WL",
        image: "ipfs://QmNZb1qc7dY8m1zRgwfqTEztUxdF9eL9h666tbK95cAwP3",
        Discord: "https://discord.gg/MyProject",
        Twitter: "https://twitter.com/MyProject",
        Website: "https://myproject.com",
        mediaType: "image/png",
        description: "My cool NFT project description",
      },
      output: {},
      assetName: "CETARDIOwhitelist4",
      validatorId: "key-traits",
    },
  ]);
});
