import { assertEquals } from "@std/assert";
import { join } from "node:path";
import { readFileSync } from "node:fs";

import { mapping, Validator } from "../../src/mod.ts";

Deno.test("TestCornucopias", () => {
  const metadata = [
    JSON.parse(
      readFileSync(join("__tests__", "payloads", "cornucopias.json"), "utf8"),
    ),
  ];

  const validatorsReceivedFromFrontend: Array<keyof typeof mapping> = [
    "hasRequiredKeysValidator",
    "compareRootKeys",
    "compareRootValues",
    "keyLowerCase",
    "keyAttributesValidator",
    "compareAttributesKeys",
    "keyWhiteSpace",
    "keyNameValidator",
    "keyLength",
    "keyMediaTypeValidator",
    "keyMediaValidator",
    "keyImageValidator",
    "keyFilesValidator",
    "keyDescriptionValidator",
    "keyAlphanumeric",
    "duplicateImage",
    "duplicateAssetName",
    "duplicateKeysValidator",
    "keyTraitsValidator",
  ];

  const mainValidator = new Validator("Main");
  for (const validator of validatorsReceivedFromFrontend) {
    mainValidator.Enable(new mapping[validator]());
  }

  for (const asset_metadata of metadata) {
    mainValidator.Execute(
      Object.keys(asset_metadata)[0],
      Object.values(asset_metadata)[0],
      metadata,
    );
  }

  const result = mainValidator.GetResults();

  assertEquals(result, [
    {
      state: "success",
      message: "All required keys are present.",
      input: {
        id: "00538",
        tag: "CFN00538",
        name: "File Node Access Key #00538",
        image: "ipfs://QmfRJmAwRV6uAEmLUx6k7c2JmhsQiHk9gy93JYpoDXiPJQ",
        media: {
          Website: "https://www.cornucopias.io",
          "Link Tree": "https://linktr.ee/CornucopiasGame",
        },
        gameid: "CFNAK",
        season: "None",
        version: "1.0",
        fullName: "File Node Access Key #00538",
        mediaType: "image/png",
        typeClass: "Access",
        attributes: { NodeType: "File Node" },
        description: "Cornucopias Node",
        projectName: "Cornucopias Game",
      },
      output: undefined,
      assetName: "CFN00538",
      validatorId: "has-required-keys",
    },
    {
      state: "success",
      message: "No similar keys found.",
      input: {
        id: "00538",
        tag: "CFN00538",
        name: "File Node Access Key #00538",
        image: "ipfs://QmfRJmAwRV6uAEmLUx6k7c2JmhsQiHk9gy93JYpoDXiPJQ",
        media: {
          Website: "https://www.cornucopias.io",
          "Link Tree": "https://linktr.ee/CornucopiasGame",
        },
        gameid: "CFNAK",
        season: "None",
        version: "1.0",
        fullName: "File Node Access Key #00538",
        mediaType: "image/png",
        typeClass: "Access",
        attributes: { NodeType: "File Node" },
        description: "Cornucopias Node",
        projectName: "Cornucopias Game",
      },
      output: undefined,
      assetName: "CFN00538",
      validatorId: "compare-root-keys",
    },
    {
      state: "success",
      message: "No similar values found.",
      input: {
        id: "00538",
        tag: "CFN00538",
        name: "File Node Access Key #00538",
        image: "ipfs://QmfRJmAwRV6uAEmLUx6k7c2JmhsQiHk9gy93JYpoDXiPJQ",
        media: {
          Website: "https://www.cornucopias.io",
          "Link Tree": "https://linktr.ee/CornucopiasGame",
        },
        gameid: "CFNAK",
        season: "None",
        version: "1.0",
        fullName: "File Node Access Key #00538",
        mediaType: "image/png",
        typeClass: "Access",
        attributes: { NodeType: "File Node" },
        description: "Cornucopias Node",
        projectName: "Cornucopias Game",
      },
      output: undefined,
      assetName: "CFN00538",
      validatorId: "compare-root-values",
    },
    {
      state: "warning",
      message: {
        message: "Some keys do not adhere to Lower Case formatting.",
        warnings: [
          { key: "Website", path: "media.Website" },
          { key: "Link Tree", path: "media.Link Tree" },
          { key: "fullName", path: "fullName" },
          { key: "mediaType", path: "mediaType" },
          { key: "typeClass", path: "typeClass" },
          { key: "NodeType", path: "attributes.NodeType" },
          { key: "projectName", path: "projectName" },
        ],
      },
      input: {
        id: "00538",
        tag: "CFN00538",
        name: "File Node Access Key #00538",
        image: "ipfs://QmfRJmAwRV6uAEmLUx6k7c2JmhsQiHk9gy93JYpoDXiPJQ",
        media: {
          Website: "https://www.cornucopias.io",
          "Link Tree": "https://linktr.ee/CornucopiasGame",
        },
        gameid: "CFNAK",
        season: "None",
        version: "1.0",
        fullName: "File Node Access Key #00538",
        mediaType: "image/png",
        typeClass: "Access",
        attributes: { NodeType: "File Node" },
        description: "Cornucopias Node",
        projectName: "Cornucopias Game",
      },
      output: undefined,
      assetName: "CFN00538",
      validatorId: "key-lower-case",
    },
    {
      state: "success",
      message: "`attributes` field is valid.",
      input: {
        id: "00538",
        tag: "CFN00538",
        name: "File Node Access Key #00538",
        image: "ipfs://QmfRJmAwRV6uAEmLUx6k7c2JmhsQiHk9gy93JYpoDXiPJQ",
        media: {
          Website: "https://www.cornucopias.io",
          "Link Tree": "https://linktr.ee/CornucopiasGame",
        },
        gameid: "CFNAK",
        season: "None",
        version: "1.0",
        fullName: "File Node Access Key #00538",
        mediaType: "image/png",
        typeClass: "Access",
        attributes: { NodeType: "File Node" },
        description: "Cornucopias Node",
        projectName: "Cornucopias Game",
      },
      output: { attributes: { NodeType: "File Node" } },
      assetName: "CFN00538",
      validatorId: "key-attributes",
    },
    {
      state: "success",
      message: "No similar keys found.",
      input: {
        id: "00538",
        tag: "CFN00538",
        name: "File Node Access Key #00538",
        image: "ipfs://QmfRJmAwRV6uAEmLUx6k7c2JmhsQiHk9gy93JYpoDXiPJQ",
        media: {
          Website: "https://www.cornucopias.io",
          "Link Tree": "https://linktr.ee/CornucopiasGame",
        },
        gameid: "CFNAK",
        season: "None",
        version: "1.0",
        fullName: "File Node Access Key #00538",
        mediaType: "image/png",
        typeClass: "Access",
        attributes: { NodeType: "File Node" },
        description: "Cornucopias Node",
        projectName: "Cornucopias Game",
      },
      output: undefined,
      assetName: "CFN00538",
      validatorId: "compare-attributes-keys",
    },
    {
      state: "success",
      message: "All checks passed. No issues detected.",
      input: {
        id: "00538",
        tag: "CFN00538",
        name: "File Node Access Key #00538",
        image: "ipfs://QmfRJmAwRV6uAEmLUx6k7c2JmhsQiHk9gy93JYpoDXiPJQ",
        media: {
          Website: "https://www.cornucopias.io",
          "Link Tree": "https://linktr.ee/CornucopiasGame",
        },
        gameid: "CFNAK",
        season: "None",
        version: "1.0",
        fullName: "File Node Access Key #00538",
        mediaType: "image/png",
        typeClass: "Access",
        attributes: { NodeType: "File Node" },
        description: "Cornucopias Node",
        projectName: "Cornucopias Game",
      },
      output: undefined,
      assetName: "CFN00538",
      validatorId: "key-white-space",
    },
    {
      state: "success",
      message: "`name` field is valid.",
      input: {
        id: "00538",
        tag: "CFN00538",
        name: "File Node Access Key #00538",
        image: "ipfs://QmfRJmAwRV6uAEmLUx6k7c2JmhsQiHk9gy93JYpoDXiPJQ",
        media: {
          Website: "https://www.cornucopias.io",
          "Link Tree": "https://linktr.ee/CornucopiasGame",
        },
        gameid: "CFNAK",
        season: "None",
        version: "1.0",
        fullName: "File Node Access Key #00538",
        mediaType: "image/png",
        typeClass: "Access",
        attributes: { NodeType: "File Node" },
        description: "Cornucopias Node",
        projectName: "Cornucopias Game",
      },
      output: { name: "File Node Access Key #00538" },
      assetName: "CFN00538",
      validatorId: "key-name",
    },
    {
      state: "success",
      message: "All checks passed. No issues detected.",
      input: {
        id: "00538",
        tag: "CFN00538",
        name: "File Node Access Key #00538",
        image: "ipfs://QmfRJmAwRV6uAEmLUx6k7c2JmhsQiHk9gy93JYpoDXiPJQ",
        media: {
          Website: "https://www.cornucopias.io",
          "Link Tree": "https://linktr.ee/CornucopiasGame",
        },
        gameid: "CFNAK",
        season: "None",
        version: "1.0",
        fullName: "File Node Access Key #00538",
        mediaType: "image/png",
        typeClass: "Access",
        attributes: { NodeType: "File Node" },
        description: "Cornucopias Node",
        projectName: "Cornucopias Game",
      },
      output: undefined,
      assetName: "CFN00538",
      validatorId: "key-length",
    },
    {
      state: "success",
      message: "`mediaType` field is valid.",
      input: {
        id: "00538",
        tag: "CFN00538",
        name: "File Node Access Key #00538",
        image: "ipfs://QmfRJmAwRV6uAEmLUx6k7c2JmhsQiHk9gy93JYpoDXiPJQ",
        media: {
          Website: "https://www.cornucopias.io",
          "Link Tree": "https://linktr.ee/CornucopiasGame",
        },
        gameid: "CFNAK",
        season: "None",
        version: "1.0",
        fullName: "File Node Access Key #00538",
        mediaType: "image/png",
        typeClass: "Access",
        attributes: { NodeType: "File Node" },
        description: "Cornucopias Node",
        projectName: "Cornucopias Game",
      },
      output: { mediaType: "image/png" },
      assetName: "CFN00538",
      validatorId: "key-media-type",
    },
    {
      state: "success",
      message: "`media` field is valid.",
      input: {
        id: "00538",
        tag: "CFN00538",
        name: "File Node Access Key #00538",
        image: "ipfs://QmfRJmAwRV6uAEmLUx6k7c2JmhsQiHk9gy93JYpoDXiPJQ",
        media: {
          Website: "https://www.cornucopias.io",
          "Link Tree": "https://linktr.ee/CornucopiasGame",
        },
        gameid: "CFNAK",
        season: "None",
        version: "1.0",
        fullName: "File Node Access Key #00538",
        mediaType: "image/png",
        typeClass: "Access",
        attributes: { NodeType: "File Node" },
        description: "Cornucopias Node",
        projectName: "Cornucopias Game",
      },
      output: {
        media: {
          Website: "https://www.cornucopias.io",
          "Link Tree": "https://linktr.ee/CornucopiasGame",
        },
      },
      assetName: "CFN00538",
      validatorId: "key-media",
    },
    {
      state: "success",
      message: "`image` field is valid.",
      input: {
        id: "00538",
        tag: "CFN00538",
        name: "File Node Access Key #00538",
        image: "ipfs://QmfRJmAwRV6uAEmLUx6k7c2JmhsQiHk9gy93JYpoDXiPJQ",
        media: {
          Website: "https://www.cornucopias.io",
          "Link Tree": "https://linktr.ee/CornucopiasGame",
        },
        gameid: "CFNAK",
        season: "None",
        version: "1.0",
        fullName: "File Node Access Key #00538",
        mediaType: "image/png",
        typeClass: "Access",
        attributes: { NodeType: "File Node" },
        description: "Cornucopias Node",
        projectName: "Cornucopias Game",
      },
      output: {
        image: "ipfs://QmfRJmAwRV6uAEmLUx6k7c2JmhsQiHk9gy93JYpoDXiPJQ",
      },
      assetName: "CFN00538",
      validatorId: "key-image",
    },
    {
      state: "success",
      message: "`files` field is valid.",
      input: {
        id: "00538",
        tag: "CFN00538",
        name: "File Node Access Key #00538",
        image: "ipfs://QmfRJmAwRV6uAEmLUx6k7c2JmhsQiHk9gy93JYpoDXiPJQ",
        media: {
          Website: "https://www.cornucopias.io",
          "Link Tree": "https://linktr.ee/CornucopiasGame",
        },
        gameid: "CFNAK",
        season: "None",
        version: "1.0",
        fullName: "File Node Access Key #00538",
        mediaType: "image/png",
        typeClass: "Access",
        attributes: { NodeType: "File Node" },
        description: "Cornucopias Node",
        projectName: "Cornucopias Game",
      },
      output: {},
      assetName: "CFN00538",
      validatorId: "key-files",
    },
    {
      state: "success",
      message: "`description` field is valid.",
      input: {
        id: "00538",
        tag: "CFN00538",
        name: "File Node Access Key #00538",
        image: "ipfs://QmfRJmAwRV6uAEmLUx6k7c2JmhsQiHk9gy93JYpoDXiPJQ",
        media: {
          Website: "https://www.cornucopias.io",
          "Link Tree": "https://linktr.ee/CornucopiasGame",
        },
        gameid: "CFNAK",
        season: "None",
        version: "1.0",
        fullName: "File Node Access Key #00538",
        mediaType: "image/png",
        typeClass: "Access",
        attributes: { NodeType: "File Node" },
        description: "Cornucopias Node",
        projectName: "Cornucopias Game",
      },
      output: { description: "Cornucopias Node" },
      assetName: "CFN00538",
      validatorId: "key-description",
    },
    {
      state: "warning",
      message: {
        message:
          "Only alphanumeric characters, dashes, and underscores are allowed for the key.",
        warnings: [{ key: "Link Tree", path: "media.Link Tree" }],
      },
      input: {
        id: "00538",
        tag: "CFN00538",
        name: "File Node Access Key #00538",
        image: "ipfs://QmfRJmAwRV6uAEmLUx6k7c2JmhsQiHk9gy93JYpoDXiPJQ",
        media: {
          Website: "https://www.cornucopias.io",
          "Link Tree": "https://linktr.ee/CornucopiasGame",
        },
        gameid: "CFNAK",
        season: "None",
        version: "1.0",
        fullName: "File Node Access Key #00538",
        mediaType: "image/png",
        typeClass: "Access",
        attributes: { NodeType: "File Node" },
        description: "Cornucopias Node",
        projectName: "Cornucopias Game",
      },
      output: undefined,
      assetName: "CFN00538",
      validatorId: "key-alphanumeric",
    },
    {
      state: "success",
      message: "All checks passed. No issues detected.",
      input: {
        id: "00538",
        tag: "CFN00538",
        name: "File Node Access Key #00538",
        image: "ipfs://QmfRJmAwRV6uAEmLUx6k7c2JmhsQiHk9gy93JYpoDXiPJQ",
        media: {
          Website: "https://www.cornucopias.io",
          "Link Tree": "https://linktr.ee/CornucopiasGame",
        },
        gameid: "CFNAK",
        season: "None",
        version: "1.0",
        fullName: "File Node Access Key #00538",
        mediaType: "image/png",
        typeClass: "Access",
        attributes: { NodeType: "File Node" },
        description: "Cornucopias Node",
        projectName: "Cornucopias Game",
      },
      output: undefined,
      assetName: "CFN00538",
      validatorId: "duplicate-image",
    },
    {
      state: "success",
      message: "All checks passed. No issues detected.",
      input: {
        id: "00538",
        tag: "CFN00538",
        name: "File Node Access Key #00538",
        image: "ipfs://QmfRJmAwRV6uAEmLUx6k7c2JmhsQiHk9gy93JYpoDXiPJQ",
        media: {
          Website: "https://www.cornucopias.io",
          "Link Tree": "https://linktr.ee/CornucopiasGame",
        },
        gameid: "CFNAK",
        season: "None",
        version: "1.0",
        fullName: "File Node Access Key #00538",
        mediaType: "image/png",
        typeClass: "Access",
        attributes: { NodeType: "File Node" },
        description: "Cornucopias Node",
        projectName: "Cornucopias Game",
      },
      output: undefined,
      assetName: "CFN00538",
      validatorId: "duplicate-asset-name",
    },
    {
      state: "success",
      message: "No significant duplicates detected in the metadata.",
      input: {
        id: "00538",
        tag: "CFN00538",
        name: "File Node Access Key #00538",
        image: "ipfs://QmfRJmAwRV6uAEmLUx6k7c2JmhsQiHk9gy93JYpoDXiPJQ",
        media: {
          Website: "https://www.cornucopias.io",
          "Link Tree": "https://linktr.ee/CornucopiasGame",
        },
        gameid: "CFNAK",
        season: "None",
        version: "1.0",
        fullName: "File Node Access Key #00538",
        mediaType: "image/png",
        typeClass: "Access",
        attributes: { NodeType: "File Node" },
        description: "Cornucopias Node",
        projectName: "Cornucopias Game",
      },
      output: undefined,
      assetName: "CFN00538",
      validatorId: "duplicate-keys",
    },
    {
      state: "success",
      message: "`traits` field is valid.",
      input: {
        id: "00538",
        tag: "CFN00538",
        name: "File Node Access Key #00538",
        image: "ipfs://QmfRJmAwRV6uAEmLUx6k7c2JmhsQiHk9gy93JYpoDXiPJQ",
        media: {
          Website: "https://www.cornucopias.io",
          "Link Tree": "https://linktr.ee/CornucopiasGame",
        },
        gameid: "CFNAK",
        season: "None",
        version: "1.0",
        fullName: "File Node Access Key #00538",
        mediaType: "image/png",
        typeClass: "Access",
        attributes: { NodeType: "File Node" },
        description: "Cornucopias Node",
        projectName: "Cornucopias Game",
      },
      output: {},
      assetName: "CFN00538",
      validatorId: "key-traits",
    },
  ]);
});
