import { assertEquals } from "@std/assert";
import { join } from "node:path";
import { readFileSync } from "node:fs";

import { mapping, Validator } from "../../src/mod.ts";

Deno.test("TestDeadpxlz", () => {
  const metadata = [
    JSON.parse(
      readFileSync(join("__tests__", "payloads", "deadpxlz.json"), "utf8"),
    ),
  ];

  const validatorsReceivedFromFrontend: Array<keyof typeof mapping> = [
    "hasRequiredKeysValidator",
    "compareRootKeys",
    "compareRootValues",
    "keyLowerCase",
    "keyAttributesValidator",
    "compareAttributesKeys",
    "keyWhiteSpace",
    "keyNameValidator",
    "keyLength",
    "keyMediaTypeValidator",
    "keyMediaValidator",
    "keyImageValidator",
    "keyFilesValidator",
    "keyDescriptionValidator",
    "keyAlphanumeric",
    "duplicateImage",
    "duplicateAssetName",
    "duplicateKeysValidator",
    "keyTraitsValidator",
  ];

  const mainValidator = new Validator("Main");
  for (const validator of validatorsReceivedFromFrontend) {
    mainValidator.Enable(new mapping[validator]());
  }

  for (const asset_metadata of metadata) {
    mainValidator.Execute(
      Object.keys(asset_metadata)[0],
      Object.values(asset_metadata)[0],
      metadata,
    );
  }

  const result = mainValidator.GetResults();

  assertEquals(result, [
    {
      state: "success",
      message: "All required keys are present.",
      input: {
        src: "ipfs://ipfs/QmV7s1iDRhiwd9dXSbehVgmbq3yvjb7rZMmYjcfRFskL68",
        name: "PXL#9951",
        tags: [
          "chain",
          "cigarette",
          "clubmasters",
          "diamond earrings",
          "slim bandana",
        ],
        type: "text/html",
        image: "ipfs://ipfs/QmRyJdBruSCaJyvKWyrroP4mMQGAitLTo27Qfkr7g65re4",
        properties: [{ key: "type", value: "dead" }],
      },
      output: undefined,
      assetName: "PXL9951",
      validatorId: "has-required-keys",
    },
    {
      state: "success",
      message: "No similar keys found.",
      input: {
        src: "ipfs://ipfs/QmV7s1iDRhiwd9dXSbehVgmbq3yvjb7rZMmYjcfRFskL68",
        name: "PXL#9951",
        tags: [
          "chain",
          "cigarette",
          "clubmasters",
          "diamond earrings",
          "slim bandana",
        ],
        type: "text/html",
        image: "ipfs://ipfs/QmRyJdBruSCaJyvKWyrroP4mMQGAitLTo27Qfkr7g65re4",
        properties: [{ key: "type", value: "dead" }],
      },
      output: undefined,
      assetName: "PXL9951",
      validatorId: "compare-root-keys",
    },
    {
      state: "success",
      message: "No similar values found.",
      input: {
        src: "ipfs://ipfs/QmV7s1iDRhiwd9dXSbehVgmbq3yvjb7rZMmYjcfRFskL68",
        name: "PXL#9951",
        tags: [
          "chain",
          "cigarette",
          "clubmasters",
          "diamond earrings",
          "slim bandana",
        ],
        type: "text/html",
        image: "ipfs://ipfs/QmRyJdBruSCaJyvKWyrroP4mMQGAitLTo27Qfkr7g65re4",
        properties: [{ key: "type", value: "dead" }],
      },
      output: undefined,
      assetName: "PXL9951",
      validatorId: "compare-root-values",
    },
    {
      state: "success",
      message: "All checks passed. No issues detected.",
      input: {
        src: "ipfs://ipfs/QmV7s1iDRhiwd9dXSbehVgmbq3yvjb7rZMmYjcfRFskL68",
        name: "PXL#9951",
        tags: [
          "chain",
          "cigarette",
          "clubmasters",
          "diamond earrings",
          "slim bandana",
        ],
        type: "text/html",
        image: "ipfs://ipfs/QmRyJdBruSCaJyvKWyrroP4mMQGAitLTo27Qfkr7g65re4",
        properties: [{ key: "type", value: "dead" }],
      },
      output: undefined,
      assetName: "PXL9951",
      validatorId: "key-lower-case",
    },
    {
      state: "success",
      message: "`attributes` field is valid.",
      input: {
        src: "ipfs://ipfs/QmV7s1iDRhiwd9dXSbehVgmbq3yvjb7rZMmYjcfRFskL68",
        name: "PXL#9951",
        tags: [
          "chain",
          "cigarette",
          "clubmasters",
          "diamond earrings",
          "slim bandana",
        ],
        type: "text/html",
        image: "ipfs://ipfs/QmRyJdBruSCaJyvKWyrroP4mMQGAitLTo27Qfkr7g65re4",
        properties: [{ key: "type", value: "dead" }],
      },
      output: {},
      assetName: "PXL9951",
      validatorId: "key-attributes",
    },
    {
      state: "warning",
      message: [
        "The `attributes` key might be missing from the supplied metadata, or an invalid threshold value may have been set.",
      ],
      input: {
        src: "ipfs://ipfs/QmV7s1iDRhiwd9dXSbehVgmbq3yvjb7rZMmYjcfRFskL68",
        name: "PXL#9951",
        tags: [
          "chain",
          "cigarette",
          "clubmasters",
          "diamond earrings",
          "slim bandana",
        ],
        type: "text/html",
        image: "ipfs://ipfs/QmRyJdBruSCaJyvKWyrroP4mMQGAitLTo27Qfkr7g65re4",
        properties: [{ key: "type", value: "dead" }],
      },
      output: undefined,
      assetName: "PXL9951",
      validatorId: "compare-attributes-keys",
    },
    {
      state: "success",
      message: "All checks passed. No issues detected.",
      input: {
        src: "ipfs://ipfs/QmV7s1iDRhiwd9dXSbehVgmbq3yvjb7rZMmYjcfRFskL68",
        name: "PXL#9951",
        tags: [
          "chain",
          "cigarette",
          "clubmasters",
          "diamond earrings",
          "slim bandana",
        ],
        type: "text/html",
        image: "ipfs://ipfs/QmRyJdBruSCaJyvKWyrroP4mMQGAitLTo27Qfkr7g65re4",
        properties: [{ key: "type", value: "dead" }],
      },
      output: undefined,
      assetName: "PXL9951",
      validatorId: "key-white-space",
    },
    {
      state: "success",
      message: "`name` field is valid.",
      input: {
        src: "ipfs://ipfs/QmV7s1iDRhiwd9dXSbehVgmbq3yvjb7rZMmYjcfRFskL68",
        name: "PXL#9951",
        tags: [
          "chain",
          "cigarette",
          "clubmasters",
          "diamond earrings",
          "slim bandana",
        ],
        type: "text/html",
        image: "ipfs://ipfs/QmRyJdBruSCaJyvKWyrroP4mMQGAitLTo27Qfkr7g65re4",
        properties: [{ key: "type", value: "dead" }],
      },
      output: { name: "PXL#9951" },
      assetName: "PXL9951",
      validatorId: "key-name",
    },
    {
      state: "success",
      message: "All checks passed. No issues detected.",
      input: {
        src: "ipfs://ipfs/QmV7s1iDRhiwd9dXSbehVgmbq3yvjb7rZMmYjcfRFskL68",
        name: "PXL#9951",
        tags: [
          "chain",
          "cigarette",
          "clubmasters",
          "diamond earrings",
          "slim bandana",
        ],
        type: "text/html",
        image: "ipfs://ipfs/QmRyJdBruSCaJyvKWyrroP4mMQGAitLTo27Qfkr7g65re4",
        properties: [{ key: "type", value: "dead" }],
      },
      output: undefined,
      assetName: "PXL9951",
      validatorId: "key-length",
    },
    {
      message: "`mediaType` field is valid.",
      output: {},
      state: "success",
      input: {
        src: "ipfs://ipfs/QmV7s1iDRhiwd9dXSbehVgmbq3yvjb7rZMmYjcfRFskL68",
        name: "PXL#9951",
        tags: [
          "chain",
          "cigarette",
          "clubmasters",
          "diamond earrings",
          "slim bandana",
        ],
        type: "text/html",
        image: "ipfs://ipfs/QmRyJdBruSCaJyvKWyrroP4mMQGAitLTo27Qfkr7g65re4",
        properties: [{ key: "type", value: "dead" }],
      },
      assetName: "PXL9951",
      validatorId: "key-media-type",
    },
    {
      state: "success",
      message: "`media` field is valid.",
      input: {
        src: "ipfs://ipfs/QmV7s1iDRhiwd9dXSbehVgmbq3yvjb7rZMmYjcfRFskL68",
        name: "PXL#9951",
        tags: [
          "chain",
          "cigarette",
          "clubmasters",
          "diamond earrings",
          "slim bandana",
        ],
        type: "text/html",
        image: "ipfs://ipfs/QmRyJdBruSCaJyvKWyrroP4mMQGAitLTo27Qfkr7g65re4",
        properties: [{ key: "type", value: "dead" }],
      },
      output: {},
      assetName: "PXL9951",
      validatorId: "key-media",
    },
    {
      state: "success",
      message: "`image` field is valid.",
      input: {
        src: "ipfs://ipfs/QmV7s1iDRhiwd9dXSbehVgmbq3yvjb7rZMmYjcfRFskL68",
        name: "PXL#9951",
        tags: [
          "chain",
          "cigarette",
          "clubmasters",
          "diamond earrings",
          "slim bandana",
        ],
        type: "text/html",
        image: "ipfs://ipfs/QmRyJdBruSCaJyvKWyrroP4mMQGAitLTo27Qfkr7g65re4",
        properties: [{ key: "type", value: "dead" }],
      },
      output: {
        image: "ipfs://ipfs/QmRyJdBruSCaJyvKWyrroP4mMQGAitLTo27Qfkr7g65re4",
      },
      assetName: "PXL9951",
      validatorId: "key-image",
    },
    {
      state: "success",
      message: "`files` field is valid.",
      input: {
        src: "ipfs://ipfs/QmV7s1iDRhiwd9dXSbehVgmbq3yvjb7rZMmYjcfRFskL68",
        name: "PXL#9951",
        tags: [
          "chain",
          "cigarette",
          "clubmasters",
          "diamond earrings",
          "slim bandana",
        ],
        type: "text/html",
        image: "ipfs://ipfs/QmRyJdBruSCaJyvKWyrroP4mMQGAitLTo27Qfkr7g65re4",
        properties: [{ key: "type", value: "dead" }],
      },
      output: {},
      assetName: "PXL9951",
      validatorId: "key-files",
    },
    {
      state: "success",
      message: "`description` field is valid.",
      input: {
        src: "ipfs://ipfs/QmV7s1iDRhiwd9dXSbehVgmbq3yvjb7rZMmYjcfRFskL68",
        name: "PXL#9951",
        tags: [
          "chain",
          "cigarette",
          "clubmasters",
          "diamond earrings",
          "slim bandana",
        ],
        type: "text/html",
        image: "ipfs://ipfs/QmRyJdBruSCaJyvKWyrroP4mMQGAitLTo27Qfkr7g65re4",
        properties: [{ key: "type", value: "dead" }],
      },
      output: {},
      assetName: "PXL9951",
      validatorId: "key-description",
    },
    {
      state: "success",
      message: "All checks passed. No issues detected.",
      input: {
        src: "ipfs://ipfs/QmV7s1iDRhiwd9dXSbehVgmbq3yvjb7rZMmYjcfRFskL68",
        name: "PXL#9951",
        tags: [
          "chain",
          "cigarette",
          "clubmasters",
          "diamond earrings",
          "slim bandana",
        ],
        type: "text/html",
        image: "ipfs://ipfs/QmRyJdBruSCaJyvKWyrroP4mMQGAitLTo27Qfkr7g65re4",
        properties: [{ key: "type", value: "dead" }],
      },
      output: undefined,
      assetName: "PXL9951",
      validatorId: "key-alphanumeric",
    },
    {
      state: "success",
      message: "All checks passed. No issues detected.",
      input: {
        src: "ipfs://ipfs/QmV7s1iDRhiwd9dXSbehVgmbq3yvjb7rZMmYjcfRFskL68",
        name: "PXL#9951",
        tags: [
          "chain",
          "cigarette",
          "clubmasters",
          "diamond earrings",
          "slim bandana",
        ],
        type: "text/html",
        image: "ipfs://ipfs/QmRyJdBruSCaJyvKWyrroP4mMQGAitLTo27Qfkr7g65re4",
        properties: [{ key: "type", value: "dead" }],
      },
      output: undefined,
      assetName: "PXL9951",
      validatorId: "duplicate-image",
    },
    {
      state: "success",
      message: "All checks passed. No issues detected.",
      input: {
        src: "ipfs://ipfs/QmV7s1iDRhiwd9dXSbehVgmbq3yvjb7rZMmYjcfRFskL68",
        name: "PXL#9951",
        tags: [
          "chain",
          "cigarette",
          "clubmasters",
          "diamond earrings",
          "slim bandana",
        ],
        type: "text/html",
        image: "ipfs://ipfs/QmRyJdBruSCaJyvKWyrroP4mMQGAitLTo27Qfkr7g65re4",
        properties: [{ key: "type", value: "dead" }],
      },
      output: undefined,
      assetName: "PXL9951",
      validatorId: "duplicate-asset-name",
    },
    {
      state: "success",
      message: "No significant duplicates detected in the metadata.",
      input: {
        src: "ipfs://ipfs/QmV7s1iDRhiwd9dXSbehVgmbq3yvjb7rZMmYjcfRFskL68",
        name: "PXL#9951",
        tags: [
          "chain",
          "cigarette",
          "clubmasters",
          "diamond earrings",
          "slim bandana",
        ],
        type: "text/html",
        image: "ipfs://ipfs/QmRyJdBruSCaJyvKWyrroP4mMQGAitLTo27Qfkr7g65re4",
        properties: [{ key: "type", value: "dead" }],
      },
      output: undefined,
      assetName: "PXL9951",
      validatorId: "duplicate-keys",
    },
    {
      state: "success",
      message: "`traits` field is valid.",
      input: {
        src: "ipfs://ipfs/QmV7s1iDRhiwd9dXSbehVgmbq3yvjb7rZMmYjcfRFskL68",
        name: "PXL#9951",
        tags: [
          "chain",
          "cigarette",
          "clubmasters",
          "diamond earrings",
          "slim bandana",
        ],
        type: "text/html",
        image: "ipfs://ipfs/QmRyJdBruSCaJyvKWyrroP4mMQGAitLTo27Qfkr7g65re4",
        properties: [{ key: "type", value: "dead" }],
      },
      output: {},
      assetName: "PXL9951",
      validatorId: "key-traits",
    },
  ]);
});
