import { assertEquals } from "@std/assert";
import { join } from "node:path";
import { readFileSync } from "node:fs";

import { mapping, Validator } from "../../src/mod.ts";

Deno.test("TestKwic", () => {
  const metadata = [
    JSON.parse(
      readFileSync(join("__tests__", "payloads", "kwic.json"), "utf8"),
    ),
  ];

  const validatorsReceivedFromFrontend: Array<keyof typeof mapping> = [
    "hasRequiredKeysValidator",
    "compareRootKeys",
    "compareRootValues",
    "keyTitleCase",
    "keyCamelCase",
    "keyWhiteSpace",
    "keyNameValidator",
    "keyLength",
    "keyMediaTypeValidator",
    "keyMediaValidator",
    "keyImageValidator",
    "keyFilesValidator",
    "keyDescriptionValidator",
    "keyAlphanumeric",
    "duplicateImage",
    "duplicateAssetName",
    "duplicateKeysValidator",
  ];

  const mainValidator = new Validator("Main");
  for (const validator of validatorsReceivedFromFrontend) {
    mainValidator.Enable(new mapping[validator]());
  }

  for (const asset_metadata of metadata) {
    mainValidator.Execute(
      Object.keys(asset_metadata)[0],
      Object.values(asset_metadata)[0],
      metadata,
    );
  }

  const result = mainValidator.GetResults();

  assertEquals(result, [
    {
      state: "success",
      message: "All required keys are present.",
      input: {
        Body: "Invader Yellow",
        Head: "Mike Facehug",
        Side: "Oozi Left Gold",
        name: "KWIC #4479",
        Bling: "None",
        image: "ipfs://QmbYrZjuPSeXCzVnMJhieHCmpJe8wj64ww6pxtLeqzz7uX",
        Faction: "Mike Mob",
        project: "Keyboard Warriors Internet Cafe",
        Background: "Solid Magenta",
        Foreground: "None",
        "Back Attachment": "None",
        "Head Attachment": "None",
      },
      output: undefined,
      assetName: "KWIC4479",
      validatorId: "has-required-keys",
    },
    {
      state: "success",
      message: "No similar keys found.",
      input: {
        Body: "Invader Yellow",
        Head: "Mike Facehug",
        Side: "Oozi Left Gold",
        name: "KWIC #4479",
        Bling: "None",
        image: "ipfs://QmbYrZjuPSeXCzVnMJhieHCmpJe8wj64ww6pxtLeqzz7uX",
        Faction: "Mike Mob",
        project: "Keyboard Warriors Internet Cafe",
        Background: "Solid Magenta",
        Foreground: "None",
        "Back Attachment": "None",
        "Head Attachment": "None",
      },
      output: undefined,
      assetName: "KWIC4479",
      validatorId: "compare-root-keys",
    },
    {
      state: "success",
      message: "No similar values found.",
      input: {
        Body: "Invader Yellow",
        Head: "Mike Facehug",
        Side: "Oozi Left Gold",
        name: "KWIC #4479",
        Bling: "None",
        image: "ipfs://QmbYrZjuPSeXCzVnMJhieHCmpJe8wj64ww6pxtLeqzz7uX",
        Faction: "Mike Mob",
        project: "Keyboard Warriors Internet Cafe",
        Background: "Solid Magenta",
        Foreground: "None",
        "Back Attachment": "None",
        "Head Attachment": "None",
      },
      output: undefined,
      assetName: "KWIC4479",
      validatorId: "compare-root-values",
    },
    {
      state: "warning",
      message: {
        message: "Some keys do not adhere to Title Case formatting.",
        warnings: [
          { key: "name", path: "name" },
          { key: "image", path: "image" },
          { key: "project", path: "project" },
        ],
      },
      input: {
        Body: "Invader Yellow",
        Head: "Mike Facehug",
        Side: "Oozi Left Gold",
        name: "KWIC #4479",
        Bling: "None",
        image: "ipfs://QmbYrZjuPSeXCzVnMJhieHCmpJe8wj64ww6pxtLeqzz7uX",
        Faction: "Mike Mob",
        project: "Keyboard Warriors Internet Cafe",
        Background: "Solid Magenta",
        Foreground: "None",
        "Back Attachment": "None",
        "Head Attachment": "None",
      },
      output: undefined,
      assetName: "KWIC4479",
      validatorId: "key-title-case",
    },
    {
      state: "warning",
      message: {
        message: "Some keys do not adhere to Camel Case formatting.",
        warnings: [
          { key: "Body", path: "Body" },
          { key: "Head", path: "Head" },
          { key: "Side", path: "Side" },
          { key: "Bling", path: "Bling" },
          { key: "Faction", path: "Faction" },
          { key: "Background", path: "Background" },
          { key: "Foreground", path: "Foreground" },
          { key: "Back Attachment", path: "Back Attachment" },
          { key: "Head Attachment", path: "Head Attachment" },
        ],
      },
      input: {
        Body: "Invader Yellow",
        Head: "Mike Facehug",
        Side: "Oozi Left Gold",
        name: "KWIC #4479",
        Bling: "None",
        image: "ipfs://QmbYrZjuPSeXCzVnMJhieHCmpJe8wj64ww6pxtLeqzz7uX",
        Faction: "Mike Mob",
        project: "Keyboard Warriors Internet Cafe",
        Background: "Solid Magenta",
        Foreground: "None",
        "Back Attachment": "None",
        "Head Attachment": "None",
      },
      output: undefined,
      assetName: "KWIC4479",
      validatorId: "key-camel-case",
    },
    {
      state: "success",
      message: "All checks passed. No issues detected.",
      input: {
        Body: "Invader Yellow",
        Head: "Mike Facehug",
        Side: "Oozi Left Gold",
        name: "KWIC #4479",
        Bling: "None",
        image: "ipfs://QmbYrZjuPSeXCzVnMJhieHCmpJe8wj64ww6pxtLeqzz7uX",
        Faction: "Mike Mob",
        project: "Keyboard Warriors Internet Cafe",
        Background: "Solid Magenta",
        Foreground: "None",
        "Back Attachment": "None",
        "Head Attachment": "None",
      },
      output: undefined,
      assetName: "KWIC4479",
      validatorId: "key-white-space",
    },
    {
      state: "success",
      message: "`name` field is valid.",
      input: {
        Body: "Invader Yellow",
        Head: "Mike Facehug",
        Side: "Oozi Left Gold",
        name: "KWIC #4479",
        Bling: "None",
        image: "ipfs://QmbYrZjuPSeXCzVnMJhieHCmpJe8wj64ww6pxtLeqzz7uX",
        Faction: "Mike Mob",
        project: "Keyboard Warriors Internet Cafe",
        Background: "Solid Magenta",
        Foreground: "None",
        "Back Attachment": "None",
        "Head Attachment": "None",
      },
      output: { name: "KWIC #4479" },
      assetName: "KWIC4479",
      validatorId: "key-name",
    },
    {
      state: "success",
      message: "All checks passed. No issues detected.",
      input: {
        Body: "Invader Yellow",
        Head: "Mike Facehug",
        Side: "Oozi Left Gold",
        name: "KWIC #4479",
        Bling: "None",
        image: "ipfs://QmbYrZjuPSeXCzVnMJhieHCmpJe8wj64ww6pxtLeqzz7uX",
        Faction: "Mike Mob",
        project: "Keyboard Warriors Internet Cafe",
        Background: "Solid Magenta",
        Foreground: "None",
        "Back Attachment": "None",
        "Head Attachment": "None",
      },
      output: undefined,
      assetName: "KWIC4479",
      validatorId: "key-length",
    },
    {
      state: "success",
      message: "`mediaType` field is valid.",
      input: {
        Body: "Invader Yellow",
        Head: "Mike Facehug",
        Side: "Oozi Left Gold",
        name: "KWIC #4479",
        Bling: "None",
        image: "ipfs://QmbYrZjuPSeXCzVnMJhieHCmpJe8wj64ww6pxtLeqzz7uX",
        Faction: "Mike Mob",
        project: "Keyboard Warriors Internet Cafe",
        Background: "Solid Magenta",
        Foreground: "None",
        "Back Attachment": "None",
        "Head Attachment": "None",
      },
      output: {},
      assetName: "KWIC4479",
      validatorId: "key-media-type",
    },
    {
      state: "success",
      message: "`media` field is valid.",
      input: {
        Body: "Invader Yellow",
        Head: "Mike Facehug",
        Side: "Oozi Left Gold",
        name: "KWIC #4479",
        Bling: "None",
        image: "ipfs://QmbYrZjuPSeXCzVnMJhieHCmpJe8wj64ww6pxtLeqzz7uX",
        Faction: "Mike Mob",
        project: "Keyboard Warriors Internet Cafe",
        Background: "Solid Magenta",
        Foreground: "None",
        "Back Attachment": "None",
        "Head Attachment": "None",
      },
      output: {},
      assetName: "KWIC4479",
      validatorId: "key-media",
    },
    {
      state: "success",
      message: "`image` field is valid.",
      input: {
        Body: "Invader Yellow",
        Head: "Mike Facehug",
        Side: "Oozi Left Gold",
        name: "KWIC #4479",
        Bling: "None",
        image: "ipfs://QmbYrZjuPSeXCzVnMJhieHCmpJe8wj64ww6pxtLeqzz7uX",
        Faction: "Mike Mob",
        project: "Keyboard Warriors Internet Cafe",
        Background: "Solid Magenta",
        Foreground: "None",
        "Back Attachment": "None",
        "Head Attachment": "None",
      },
      output: {
        image: "ipfs://QmbYrZjuPSeXCzVnMJhieHCmpJe8wj64ww6pxtLeqzz7uX",
      },
      assetName: "KWIC4479",
      validatorId: "key-image",
    },
    {
      state: "success",
      message: "`files` field is valid.",
      input: {
        Body: "Invader Yellow",
        Head: "Mike Facehug",
        Side: "Oozi Left Gold",
        name: "KWIC #4479",
        Bling: "None",
        image: "ipfs://QmbYrZjuPSeXCzVnMJhieHCmpJe8wj64ww6pxtLeqzz7uX",
        Faction: "Mike Mob",
        project: "Keyboard Warriors Internet Cafe",
        Background: "Solid Magenta",
        Foreground: "None",
        "Back Attachment": "None",
        "Head Attachment": "None",
      },
      output: {},
      assetName: "KWIC4479",
      validatorId: "key-files",
    },
    {
      state: "success",
      message: "`description` field is valid.",
      input: {
        Body: "Invader Yellow",
        Head: "Mike Facehug",
        Side: "Oozi Left Gold",
        name: "KWIC #4479",
        Bling: "None",
        image: "ipfs://QmbYrZjuPSeXCzVnMJhieHCmpJe8wj64ww6pxtLeqzz7uX",
        Faction: "Mike Mob",
        project: "Keyboard Warriors Internet Cafe",
        Background: "Solid Magenta",
        Foreground: "None",
        "Back Attachment": "None",
        "Head Attachment": "None",
      },
      output: {},
      assetName: "KWIC4479",
      validatorId: "key-description",
    },
    {
      state: "warning",
      message: {
        message:
          "Only alphanumeric characters, dashes, and underscores are allowed for the key.",
        warnings: [
          { key: "Back Attachment", path: "Back Attachment" },
          { key: "Head Attachment", path: "Head Attachment" },
        ],
      },
      input: {
        Body: "Invader Yellow",
        Head: "Mike Facehug",
        Side: "Oozi Left Gold",
        name: "KWIC #4479",
        Bling: "None",
        image: "ipfs://QmbYrZjuPSeXCzVnMJhieHCmpJe8wj64ww6pxtLeqzz7uX",
        Faction: "Mike Mob",
        project: "Keyboard Warriors Internet Cafe",
        Background: "Solid Magenta",
        Foreground: "None",
        "Back Attachment": "None",
        "Head Attachment": "None",
      },
      output: undefined,
      assetName: "KWIC4479",
      validatorId: "key-alphanumeric",
    },
    {
      state: "success",
      message: "All checks passed. No issues detected.",
      input: {
        Body: "Invader Yellow",
        Head: "Mike Facehug",
        Side: "Oozi Left Gold",
        name: "KWIC #4479",
        Bling: "None",
        image: "ipfs://QmbYrZjuPSeXCzVnMJhieHCmpJe8wj64ww6pxtLeqzz7uX",
        Faction: "Mike Mob",
        project: "Keyboard Warriors Internet Cafe",
        Background: "Solid Magenta",
        Foreground: "None",
        "Back Attachment": "None",
        "Head Attachment": "None",
      },
      output: undefined,
      assetName: "KWIC4479",
      validatorId: "duplicate-image",
    },
    {
      state: "success",
      message: "All checks passed. No issues detected.",
      input: {
        Body: "Invader Yellow",
        Head: "Mike Facehug",
        Side: "Oozi Left Gold",
        name: "KWIC #4479",
        Bling: "None",
        image: "ipfs://QmbYrZjuPSeXCzVnMJhieHCmpJe8wj64ww6pxtLeqzz7uX",
        Faction: "Mike Mob",
        project: "Keyboard Warriors Internet Cafe",
        Background: "Solid Magenta",
        Foreground: "None",
        "Back Attachment": "None",
        "Head Attachment": "None",
      },
      output: undefined,
      assetName: "KWIC4479",
      validatorId: "duplicate-asset-name",
    },
    {
      state: "success",
      message: "No significant duplicates detected in the metadata.",
      input: {
        Body: "Invader Yellow",
        Head: "Mike Facehug",
        Side: "Oozi Left Gold",
        name: "KWIC #4479",
        Bling: "None",
        image: "ipfs://QmbYrZjuPSeXCzVnMJhieHCmpJe8wj64ww6pxtLeqzz7uX",
        Faction: "Mike Mob",
        project: "Keyboard Warriors Internet Cafe",
        Background: "Solid Magenta",
        Foreground: "None",
        "Back Attachment": "None",
        "Head Attachment": "None",
      },
      output: undefined,
      assetName: "KWIC4479",
      validatorId: "duplicate-keys",
    },
  ]);
});
